### ISSUE TITLE
Error in the excution 

### ISSUE THREAD

**Issue by Yohan050** [andreili/cotopha_decompiler#1]
When I execute the projet after complie it, the program crash. I complied on linux and windows but the result is same.  

On linux, I have one more information : https://cdn.discordapp.com/attachments/429696516224188419/434052311753555979/unknown.png

Konsole said me that : Segmentation fault (core dumped).  I have no problem when I compile the project, but impossible to execute without fail.

I investigated for tracking the error, I arrived at the function listing_to_dir in csximage.cpp. The process stop here. I use some printf for tracing. I can enter in the function but I don't out.

I use this csx file.  I extract this for the game Oshiete Sensei Otoko no Ko Gakuen Icha Love! Otoko no Ko Triangle.
[zdcmain20L.zip](https://github.com/andreili/cotopha_decompiler/files/1913447/zdcmain20L.zip)

**Comment by andreili** [comment]
Ok, i see this error on a night...

**Comment by andreili** [comment]
@Yohan050 Fixed ;)
a0ca1d9e512323e453e7306c0ca40855ebf38f92
Fixed more errors:

- added a new field (csxfile.cpp@166, need confirmation on other games);
- parse initialization values for a global variables;
- extended PUSH VARIABLE operator;
- added a local variable (usage on CATCH blocks);
- added a absolute conditional jump (unconfirmed, need more analyze).
